version: '3.8'

# Development environment with optional PostgreSQL
# By default, only Redis starts. Use profiles to start PostgreSQL when needed.

services:
  # Redis is always needed for development
  redis:
    image: redis:7-alpine
    container_name: rcp-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # PostgreSQL for development (optional)
  # Start with: docker-compose -f docker-compose.dev.yml --profile postgres up
  postgres:
    image: postgres:15
    container_name: rcp-postgres-dev
    environment:
      POSTGRES_DB: relationship_care_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./src/database/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
    profiles:
      - postgres
      - full

volumes:
  postgres_data_dev:
  redis_data_dev: