version: '3.8'

# Base services for the Relationship Care Platform
# PostgreSQL is now optional - the application defaults to SQLite for development

services:
  # Redis is always needed for caching and session management
  redis:
    image: redis:7-alpine
    container_name: rcp-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # PostgreSQL is now optional - use profiles to control when it starts
  postgres:
    image: postgres:15
    container_name: rcp-postgres
    environment:
      POSTGRES_DB: relationship_care_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
    profiles:
      - postgres
      - full

volumes:
  postgres_data:
  redis_data: